//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseExtension
    {
        public int DatabaseID { get; set; }
        public string DatabaseSchema { get; set; }
        public string DatabaseName { get; set; }
        public string CommandPreFix { get; set; }
        public string NameSpace { get; set; }
        public string ProjectDirectory { get; set; }
        public Nullable<bool> TfsCheck { get; set; }
        public string TfsServer { get; set; }
        public string TfsUserName { get; set; }
        public string TfsPassword { get; set; }
        public string Company { get; set; }
        public string CopyRight { get; set; }
        public string Product { get; set; }
        public string GuidEntity { get; set; }
        public string GuidDal { get; set; }
        public string GuidIBiz { get; set; }
        public string GuidBiz { get; set; }
        public string GuidService { get; set; }
        public Nullable<bool> WCF { get; set; }
    }
}
