//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableExtension
    {
        public string TableName { get; set; }
        public string Description { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public Nullable<bool> Search { get; set; }
        public Nullable<bool> Create { get; set; }
        public Nullable<bool> Paging { get; set; }
        public Nullable<bool> Delete { get; set; }
        public Nullable<bool> Export { get; set; }
        public Nullable<bool> Print { get; set; }
    }
}
