//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDetailExtension
    {
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsSearch { get; set; }
        public Nullable<bool> IsRange { get; set; }
        public string PropertyType { get; set; }
    }
}
