//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_AUTO_REPORT_BAK
    {
        public System.Guid OID { get; set; }
        public string GROUPCODE { get; set; }
        public string YEARMONTH { get; set; }
        public string CURRENCY { get; set; }
        public string REPORTSNAME { get; set; }
        public string FILEURL { get; set; }
        public Nullable<System.Guid> ADDER { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ISDELETE { get; set; }
    }
}
