//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_AUTO_INFO
    {
        public System.Guid OID { get; set; }
        public Nullable<int> SORTINDEX { get; set; }
        public string PROCNAME { get; set; }
        public string PROCDESCRIPTION { get; set; }
        public string ISDISABLE { get; set; }
        public string ADDER { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public string UPDATER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string MODELNAME { get; set; }
        public string MODELURL { get; set; }
    }
}
