//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_COMPANY_DIRECTORY
    {
        public System.Guid OID { get; set; }
        public string ORDERID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string IS_CODE { get; set; }
        public string DIRECTORYTYPE { get; set; }
        public string IS_HIDE { get; set; }
        public string ISALLOWREPEATEDCODE { get; set; }
        public string ISDEFAULTCODE { get; set; }
        public Nullable<decimal> SORTINDEX { get; set; }
        public string DESCRIPTION { get; set; }
        public string ISDELETE { get; set; }
        public string ISDISABLE { get; set; }
        public string ADDER { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public string UPDATER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.Guid> PARENTOID { get; set; }
    }
}
