//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_DATA_MULTI
    {
        public System.Guid OID { get; set; }
        public Nullable<System.Guid> SUITEOID { get; set; }
        public Nullable<decimal> QUNT { get; set; }
        public Nullable<decimal> QUNTCONTRAST { get; set; }
        public Nullable<decimal> QUNTPERCENT { get; set; }
        public Nullable<decimal> QUNTSUM { get; set; }
        public Nullable<decimal> QUNTCONTRASTSUM { get; set; }
        public Nullable<decimal> QUNTSUMPERCENT { get; set; }
        public Nullable<decimal> USD { get; set; }
        public Nullable<decimal> USDCONTRAST { get; set; }
        public Nullable<decimal> USDPERCENT { get; set; }
        public Nullable<decimal> USDSUM { get; set; }
        public Nullable<decimal> USDCONTRASTSUM { get; set; }
        public Nullable<decimal> USDSUMPERCENT { get; set; }
        public Nullable<decimal> RMB { get; set; }
        public Nullable<decimal> RMBCONTRAST { get; set; }
        public Nullable<decimal> RMBPERCENT { get; set; }
        public Nullable<decimal> RMBSUM { get; set; }
        public Nullable<decimal> RMBCONTRASTSUM { get; set; }
        public Nullable<decimal> RMBSUMPERCENT { get; set; }
        public string COMPANY1 { get; set; }
        public string COMPANY2 { get; set; }
        public string COMPANY3 { get; set; }
        public string COMPANY4 { get; set; }
        public string COMPANY5 { get; set; }
        public string COMPANY6 { get; set; }
        public string COMPANY7 { get; set; }
        public string COMPANY8 { get; set; }
        public string COMPANY9 { get; set; }
        public string COMPANY10 { get; set; }
        public string COMPANY11 { get; set; }
        public string COMPANY12 { get; set; }
        public string COMPANYCODE { get; set; }
        public string HS1 { get; set; }
        public string HS2 { get; set; }
        public string HS3 { get; set; }
        public string HS4 { get; set; }
        public string HS5 { get; set; }
        public string HS6 { get; set; }
        public string HS7 { get; set; }
        public string HS8 { get; set; }
        public string HS9 { get; set; }
        public string HS10 { get; set; }
        public string HS11 { get; set; }
        public string HS12 { get; set; }
        public string HSCODE { get; set; }
        public string CUST1 { get; set; }
        public string CUST2 { get; set; }
        public string CUST3 { get; set; }
        public string CUST4 { get; set; }
        public string CUST5 { get; set; }
        public string CUST6 { get; set; }
        public string CUST7 { get; set; }
        public string CUST8 { get; set; }
        public string CUST9 { get; set; }
        public string CUST10 { get; set; }
        public string CUST11 { get; set; }
        public string CUST12 { get; set; }
        public string CUSTCODE { get; set; }
        public string COUNTRY1 { get; set; }
        public string COUNTRY2 { get; set; }
        public string COUNTRY3 { get; set; }
        public string COUNTRY4 { get; set; }
        public string COUNTRY5 { get; set; }
        public string COUNTRY6 { get; set; }
        public string COUNTRY7 { get; set; }
        public string COUNTRY8 { get; set; }
        public string COUNTRY9 { get; set; }
        public string COUNTRY10 { get; set; }
        public string COUNTRY11 { get; set; }
        public string COUNTRY12 { get; set; }
        public string COUNTRYCODE { get; set; }
        public string CONSIGN1 { get; set; }
        public string CONSIGN2 { get; set; }
        public string CONSIGN3 { get; set; }
        public string CONSIGN4 { get; set; }
        public string CONSIGN5 { get; set; }
        public string CONSIGN6 { get; set; }
        public string CONSIGN7 { get; set; }
        public string CONSIGN8 { get; set; }
        public string CONSIGN9 { get; set; }
        public string CONSIGN10 { get; set; }
        public string CONSIGN11 { get; set; }
        public string CONSIGN12 { get; set; }
        public string CONSIGNCODE { get; set; }
        public string TRADE1 { get; set; }
        public string TRADE2 { get; set; }
        public string TRADE3 { get; set; }
        public string TRADE4 { get; set; }
        public string TRADE5 { get; set; }
        public string TRADE6 { get; set; }
        public string TRADE7 { get; set; }
        public string TRADE8 { get; set; }
        public string TRADE9 { get; set; }
        public string TRADE10 { get; set; }
        public string TRADE11 { get; set; }
        public string TRADE12 { get; set; }
        public string TRADECODE { get; set; }
        public string TRANSPORT1 { get; set; }
        public string TRANSPORT2 { get; set; }
        public string TRANSPORT3 { get; set; }
        public string TRANSPORT4 { get; set; }
        public string TRANSPORT5 { get; set; }
        public string TRANSPORT6 { get; set; }
        public string TRANSPORT7 { get; set; }
        public string TRANSPORT8 { get; set; }
        public string TRANSPORT9 { get; set; }
        public string TRANSPORT10 { get; set; }
        public string TRANSPORT11 { get; set; }
        public string TRANSPORT12 { get; set; }
        public string TRANSPORTCODE { get; set; }
        public string DATATYPE { get; set; }
        public Nullable<decimal> ROWINDEX { get; set; }
    }
}
