//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_DATA_FIXED
    {
        public System.Guid OID { get; set; }
        public Nullable<System.Guid> SUITEOID { get; set; }
        public string ORDERID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> USD { get; set; }
        public Nullable<decimal> USDCONTRAST { get; set; }
        public Nullable<decimal> USDPERCENT { get; set; }
        public Nullable<decimal> USDSUM { get; set; }
        public Nullable<decimal> USDCONTRASTSUM { get; set; }
        public Nullable<decimal> USDSUMPERCENT { get; set; }
        public Nullable<decimal> RMB { get; set; }
        public Nullable<decimal> RMBCONTRAST { get; set; }
        public Nullable<decimal> RMBPERCENT { get; set; }
        public Nullable<decimal> RMBSUM { get; set; }
        public Nullable<decimal> RMBCONTRASTSUM { get; set; }
        public Nullable<decimal> RMBSUMPERCENT { get; set; }
        public Nullable<decimal> QUNT { get; set; }
        public Nullable<decimal> QUNTCONTRAST { get; set; }
        public Nullable<decimal> QUNTPERCENT { get; set; }
        public Nullable<decimal> QUNTSUM { get; set; }
        public Nullable<decimal> QUNTCONTRASTSUM { get; set; }
        public Nullable<decimal> QUNTSUMPERCENT { get; set; }
        public string DATATYPE { get; set; }
        public Nullable<decimal> ROWINDEX { get; set; }
        public Nullable<decimal> TOPPERCENT { get; set; }
        public Nullable<decimal> TOPSUMPERCENT { get; set; }
    }
}
