//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_DATA_TREND
    {
        public System.Guid OID { get; set; }
        public System.Guid SUITEOID { get; set; }
        public string ORDERID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string UNIT { get; set; }
        public string YEARMONTH { get; set; }
        public Nullable<decimal> IMPORTUSD { get; set; }
        public Nullable<decimal> IMPORTUSDCONTRAST { get; set; }
        public Nullable<decimal> IMPORTUSDPERCENT { get; set; }
        public Nullable<decimal> IMPORTUSDCONRATE { get; set; }
        public Nullable<decimal> IMPORTUSDPULLINGPOINT { get; set; }
        public Nullable<decimal> IMPORTRMB { get; set; }
        public Nullable<decimal> IMPORTRMBCONTRAST { get; set; }
        public Nullable<decimal> IMPORTRMBPERCENT { get; set; }
        public Nullable<decimal> IMPORTRMBCONRATE { get; set; }
        public Nullable<decimal> IMPORTRMBPULLINGPOINT { get; set; }
        public Nullable<decimal> IMPORTQUNT { get; set; }
        public Nullable<decimal> IMPORTQUNTCONTRAST { get; set; }
        public Nullable<decimal> IMPORTQUNTPERCENT { get; set; }
        public Nullable<decimal> IMPORTUSDUP { get; set; }
        public Nullable<decimal> IMPORTUSDUPCONTRAST { get; set; }
        public Nullable<decimal> IMPORTUSDUPPERCENT { get; set; }
        public Nullable<decimal> IMPORTRMBUP { get; set; }
        public Nullable<decimal> IMPORTRMBUPCONTRAST { get; set; }
        public Nullable<decimal> IMPORTRMBUPPERCENT { get; set; }
        public Nullable<decimal> IMPORTSUMUSD { get; set; }
        public Nullable<decimal> IMPORTSUMUSDCONTRAST { get; set; }
        public Nullable<decimal> IMPORTSUMUSDPERCENT { get; set; }
        public Nullable<decimal> IMPORTSUMUSDCONRATE { get; set; }
        public Nullable<decimal> IMPORTSUMUSDPULLINGPOINT { get; set; }
        public Nullable<decimal> IMPORTSUMRMB { get; set; }
        public Nullable<decimal> IMPORTSUMRMBCONTRAST { get; set; }
        public Nullable<decimal> IMPORTSUMRMBPERCENT { get; set; }
        public Nullable<decimal> IMPORTSUMRMBCONRATE { get; set; }
        public Nullable<decimal> IMPORTSUMRMBPULLINGPOINT { get; set; }
        public Nullable<decimal> IMPORTSUMQUNT { get; set; }
        public Nullable<decimal> IMPORTSUMQUNTCONTRAST { get; set; }
        public Nullable<decimal> IMPORTSUMQUNTPERCENT { get; set; }
        public Nullable<decimal> IMPORTSUMUSDUP { get; set; }
        public Nullable<decimal> IMPORTSUMUSDUPCONTRAST { get; set; }
        public Nullable<decimal> IMPORTSUMUSDUPPERCENT { get; set; }
        public Nullable<decimal> IMPORTSUMRMBUP { get; set; }
        public Nullable<decimal> IMPORTSUMRMBUPCONTRAST { get; set; }
        public Nullable<decimal> IMPORTSUMRMBUPPERCENT { get; set; }
        public Nullable<decimal> EXPORTUSD { get; set; }
        public Nullable<decimal> EXPORTUSDCONTRAST { get; set; }
        public Nullable<decimal> EXPORTUSDPERCENT { get; set; }
        public Nullable<decimal> EXPORTUSDCONRATE { get; set; }
        public Nullable<decimal> EXPORTUSDPULLINGPOINT { get; set; }
        public Nullable<decimal> EXPORTRMB { get; set; }
        public Nullable<decimal> EXPORTRMBCONTRAST { get; set; }
        public Nullable<decimal> EXPORTRMBPERCENT { get; set; }
        public Nullable<decimal> EXPORTRMBCONRATE { get; set; }
        public Nullable<decimal> EXPORTRMBPULLINGPOINT { get; set; }
        public Nullable<decimal> EXPORTQUNT { get; set; }
        public Nullable<decimal> EXPORTQUNTCONTRAST { get; set; }
        public Nullable<decimal> EXPORTQUNTPERCENT { get; set; }
        public Nullable<decimal> EXPORTUSDUP { get; set; }
        public Nullable<decimal> EXPORTUSDUPCONTRAST { get; set; }
        public Nullable<decimal> EXPORTUSDUPPERCENT { get; set; }
        public Nullable<decimal> EXPORTRMBUP { get; set; }
        public Nullable<decimal> EXPORTRMBUPCONTRAST { get; set; }
        public Nullable<decimal> EXPORTRMBUPPERCENT { get; set; }
        public Nullable<decimal> EXPORTSUMUSD { get; set; }
        public Nullable<decimal> EXPORTSUMUSDCONTRAST { get; set; }
        public Nullable<decimal> EXPORTSUMUSDPERCENT { get; set; }
        public Nullable<decimal> EXPORTSUMUSDCONRATE { get; set; }
        public Nullable<decimal> EXPORTSUMUSDPULLINGPOINT { get; set; }
        public Nullable<decimal> EXPORTSUMRMB { get; set; }
        public Nullable<decimal> EXPORTSUMRMBCONTRAST { get; set; }
        public Nullable<decimal> EXPORTSUMRMBPERCENT { get; set; }
        public Nullable<decimal> EXPORTSUMRMBCONRATE { get; set; }
        public Nullable<decimal> EXPORTSUMRMBPULLINGPOINT { get; set; }
        public Nullable<decimal> EXPORTSUMQUNT { get; set; }
        public Nullable<decimal> EXPORTSUMQUNTCONTRAST { get; set; }
        public Nullable<decimal> EXPORTSUMQUNTPERCENT { get; set; }
        public Nullable<decimal> EXPORTSUMUSDUP { get; set; }
        public Nullable<decimal> EXPORTSUMUSDUPCONTRAST { get; set; }
        public Nullable<decimal> EXPORTSUMUSDUPPERCENT { get; set; }
        public Nullable<decimal> EXPORTSUMRMBUP { get; set; }
        public Nullable<decimal> EXPORTSUMRMBUPCONTRAST { get; set; }
        public Nullable<decimal> EXPORTSUMRMBUPPERCENT { get; set; }
        public Nullable<decimal> IEUSD { get; set; }
        public Nullable<decimal> IEUSDCONTRAST { get; set; }
        public Nullable<decimal> IEUSDPERCENT { get; set; }
        public Nullable<decimal> IEUSDCONRATE { get; set; }
        public Nullable<decimal> IEUSDPULLINGPOINT { get; set; }
        public Nullable<decimal> IERMB { get; set; }
        public Nullable<decimal> IERMBCONTRAST { get; set; }
        public Nullable<decimal> IERMBPERCENT { get; set; }
        public Nullable<decimal> IERMBCONRATE { get; set; }
        public Nullable<decimal> IERMBPULLINGPOINT { get; set; }
        public Nullable<decimal> IEQUNT { get; set; }
        public Nullable<decimal> IEQUNTCONTRAST { get; set; }
        public Nullable<decimal> IEQUNTPERCENT { get; set; }
        public Nullable<decimal> IEUSDUP { get; set; }
        public Nullable<decimal> IEUSDUPCONTRAST { get; set; }
        public Nullable<decimal> IEUSDUPPERCENT { get; set; }
        public Nullable<decimal> IERMBUP { get; set; }
        public Nullable<decimal> IERMBUPCONTRAST { get; set; }
        public Nullable<decimal> IERMBUPPERCENT { get; set; }
        public Nullable<decimal> IESUMUSD { get; set; }
        public Nullable<decimal> IESUMUSDCONTRAST { get; set; }
        public Nullable<decimal> IESUMUSDPERCENT { get; set; }
        public Nullable<decimal> IESUMUSDCONRATE { get; set; }
        public Nullable<decimal> IESUMUSDPULLINGPOINT { get; set; }
        public Nullable<decimal> IESUMRMB { get; set; }
        public Nullable<decimal> IESUMRMBCONTRAST { get; set; }
        public Nullable<decimal> IESUMRMBPERCENT { get; set; }
        public Nullable<decimal> IESUMRMBCONRATE { get; set; }
        public Nullable<decimal> IESUMRMBPULLINGPOINT { get; set; }
        public Nullable<decimal> IESUMQUNT { get; set; }
        public Nullable<decimal> IESUMQUNTCONTRAST { get; set; }
        public Nullable<decimal> IESUMQUNTPERCENT { get; set; }
        public Nullable<decimal> IESUMUSDUP { get; set; }
        public Nullable<decimal> IESUMUSDUPCONTRAST { get; set; }
        public Nullable<decimal> IESUMUSDUPPERCENT { get; set; }
        public Nullable<decimal> IESUMRMBUP { get; set; }
        public Nullable<decimal> IESUMRMBUPCONTRAST { get; set; }
        public Nullable<decimal> IESUMRMBUPPERCENT { get; set; }
    }
}
