//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_DATA_PRICE
    {
        public System.Guid OID { get; set; }
        public System.Guid SUITEOID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> IMPORTQUNT { get; set; }
        public Nullable<decimal> IMPORTQUNTSTANDARD { get; set; }
        public Nullable<decimal> IMPORTUSD { get; set; }
        public Nullable<decimal> IMPORTRMB { get; set; }
        public Nullable<decimal> IMPORTUSDSTANDARD { get; set; }
        public Nullable<decimal> IMPORTRMBSTANDARD { get; set; }
        public Nullable<decimal> IMPORTIPMONTH { get; set; }
        public Nullable<decimal> IMPORTIQMONTH { get; set; }
        public Nullable<decimal> IMPORTIPQMONTH { get; set; }
        public Nullable<decimal> IMPORTSUMQ { get; set; }
        public Nullable<decimal> IMPORTSUMQSTANDARD { get; set; }
        public Nullable<decimal> IMPORTSUMM { get; set; }
        public Nullable<decimal> IMPORTRMBSUMM { get; set; }
        public Nullable<decimal> IMPORTSUMMSTANDARD { get; set; }
        public Nullable<decimal> IMPORTRMBSUMMSTANDARD { get; set; }
        public Nullable<decimal> IMPORTIPTOTAL { get; set; }
        public Nullable<decimal> IMPORTIQTOTAL { get; set; }
        public Nullable<decimal> IMPORTIPQTOTAL { get; set; }
        public Nullable<decimal> IMPORTPRICEPERCENTMONTH { get; set; }
        public Nullable<decimal> IMPORTPSMONTH { get; set; }
        public Nullable<decimal> IMPORTLSMONTH { get; set; }
        public Nullable<decimal> IMPORTFSMONTH { get; set; }
        public Nullable<decimal> IMPORTPRICEPERCENTTOTAL { get; set; }
        public Nullable<decimal> IMPORTPSTOTAL { get; set; }
        public Nullable<decimal> IMPORTLSTOTAL { get; set; }
        public Nullable<decimal> IMPORTFSTOTAL { get; set; }
        public Nullable<decimal> EXPORTQUNT { get; set; }
        public Nullable<decimal> EXPORTQUNTSTANDARD { get; set; }
        public Nullable<decimal> EXPORTUSD { get; set; }
        public Nullable<decimal> EXPORTRMB { get; set; }
        public Nullable<decimal> EXPORTUSDSTANDARD { get; set; }
        public Nullable<decimal> EXPORTRMBSTANDARD { get; set; }
        public Nullable<decimal> EXPORTIPMONTH { get; set; }
        public Nullable<decimal> EXPORTIQMONTH { get; set; }
        public Nullable<decimal> EXPORTIPQMONTH { get; set; }
        public Nullable<decimal> EXPORTSUMQ { get; set; }
        public Nullable<decimal> EXPORTSUMQSTANDARD { get; set; }
        public Nullable<decimal> EXPORTSUMM { get; set; }
        public Nullable<decimal> EXPORTRMBSUMM { get; set; }
        public Nullable<decimal> EXPORTSUMMSTANDARD { get; set; }
        public Nullable<decimal> EXPORTRMBSUMMSTANDARD { get; set; }
        public Nullable<decimal> EXPORTIPTOTAL { get; set; }
        public Nullable<decimal> EXPORTIQTOTAL { get; set; }
        public Nullable<decimal> EXPORTIPQTOTAL { get; set; }
        public Nullable<decimal> EXPORTPRICEPERCENTMONTH { get; set; }
        public Nullable<decimal> EXPORTPSMONTH { get; set; }
        public Nullable<decimal> EXPORTLSMONTH { get; set; }
        public Nullable<decimal> EXPORTFSMONTH { get; set; }
        public Nullable<decimal> EXPORTPRICEPERCENTTOTAL { get; set; }
        public Nullable<decimal> EXPORTPSTOTAL { get; set; }
        public Nullable<decimal> EXPORTLSTOTAL { get; set; }
        public Nullable<decimal> EXPORTFSTOTAL { get; set; }
        public string ORDERID { get; set; }
        public string PROCESSUNIT { get; set; }
        public Nullable<decimal> IMPORTIPRMBMONTH { get; set; }
        public Nullable<decimal> IMPORTIQRMBMONTH { get; set; }
        public Nullable<decimal> IMPORTIPQRMBMONTH { get; set; }
        public Nullable<decimal> IMPORTIPRMBTOTAL { get; set; }
        public Nullable<decimal> IMPORTIQRMBTOTAL { get; set; }
        public Nullable<decimal> IMPORTIPQRMBTOTAL { get; set; }
        public Nullable<decimal> IMPORTRMBPRICEPERCENTMONTH { get; set; }
        public Nullable<decimal> IMPORTPSRMBMONTH { get; set; }
        public Nullable<decimal> IMPORTLSRMBMONTH { get; set; }
        public Nullable<decimal> IMPORTFSRMBMONTH { get; set; }
        public Nullable<decimal> IMPORTRMBPRICEPERCENTTOTAL { get; set; }
        public Nullable<decimal> IMPORTPSRMBTOTAL { get; set; }
        public Nullable<decimal> IMPORTLSRMBTOTAL { get; set; }
        public Nullable<decimal> IMPORTFSRMBTOTAL { get; set; }
        public Nullable<decimal> EXPORTIPRMBMONTH { get; set; }
        public Nullable<decimal> EXPORTIQRMBMONTH { get; set; }
        public Nullable<decimal> EXPORTIPQRMBMONTH { get; set; }
        public Nullable<decimal> EXPORTIPRMBTOTAL { get; set; }
        public Nullable<decimal> EXPORTIQRMBTOTAL { get; set; }
        public Nullable<decimal> EXPORTIPQRMBTOTAL { get; set; }
        public Nullable<decimal> EXPORTRMBPRICEPERCENTMONTH { get; set; }
        public Nullable<decimal> EXPORTPSRMBMONTH { get; set; }
        public Nullable<decimal> EXPORTLSRMBMONTH { get; set; }
        public Nullable<decimal> EXPORTFSRMBMONTH { get; set; }
        public Nullable<decimal> EXPORTRMBPRICEPERCENTTOTAL { get; set; }
        public Nullable<decimal> EXPORTPSRMBTOTAL { get; set; }
        public Nullable<decimal> EXPORTLSRMBTOTAL { get; set; }
        public Nullable<decimal> EXPORTFSRMBTOTAL { get; set; }
    }
}
