//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_IMPORTDATA_VIEW_I
    {
        public System.Guid OID { get; set; }
        public string COMPANYCODE { get; set; }
        public string HSCODE { get; set; }
        public string CONSIGNCODE { get; set; }
        public string TRADECODE { get; set; }
        public string COUNTRYCODE { get; set; }
        public string CUSTCODE { get; set; }
        public string TRANSPORTCODE { get; set; }
        public Nullable<decimal> QUNT { get; set; }
        public Nullable<decimal> SUMQ { get; set; }
        public Nullable<decimal> USD { get; set; }
        public Nullable<decimal> SUMM { get; set; }
        public Nullable<decimal> RMB { get; set; }
        public Nullable<decimal> RMBSUMM { get; set; }
        public string UNITCODE { get; set; }
    }
}
