//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_IMPORTDATA_LOG
    {
        public System.Guid OID { get; set; }
        public string IMPORTTYPE { get; set; }
        public string DATATYPE { get; set; }
        public string DATADATE { get; set; }
        public Nullable<int> DATADATE2 { get; set; }
        public string CODETYPE { get; set; }
        public Nullable<System.DateTime> IMPORTDATE { get; set; }
        public string OPERATETYPE { get; set; }
        public Nullable<decimal> RECORDNUM { get; set; }
        public string ADDER { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public string LOGTYPE { get; set; }
    }
}
