//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SEARCH_TREND_DIRECTORY
    {
        public System.Guid OID { get; set; }
        public string ORDERID { get; set; }
        public Nullable<System.Guid> SUITEOID { get; set; }
    }
}
