//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SYS_EMPLOYEE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ORGID { get; set; }
        public Nullable<System.Guid> USERGUID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string EMAIL { get; set; }
        public string MOBILEPHONE { get; set; }
        public string OFFICEPHONE { get; set; }
        public string HOMEPHONE { get; set; }
        public Nullable<decimal> DUTYID { get; set; }
        public Nullable<decimal> SORTINDEX { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string ISDELETED { get; set; }
        public string ADDRESS { get; set; }
        public string ISDEPARTURE { get; set; }
        public Nullable<decimal> DEPARTURETYPE { get; set; }
        public Nullable<System.DateTime> DEPARTUREDATE { get; set; }
        public string DEPARTUREREASON { get; set; }
        public string DEPARTUREREMARK { get; set; }
        public Nullable<System.DateTime> ENTRYDATE { get; set; }
        public Nullable<decimal> ANNUALLEAVE { get; set; }
        public Nullable<decimal> OFFDAYS { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public string EMERGENCYCONTACT { get; set; }
        public string FIRSTNAME { get; set; }
        public string ELECTRONICSIGNATURE { get; set; }
        public string IMAGE { get; set; }
    }
}
