//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SYS_LOG4NET
    {
        public decimal LOGID { get; set; }
        public System.DateTime LOGTIME { get; set; }
        public string THREAD { get; set; }
        public string LOGLEVEL { get; set; }
        public string LOGGER { get; set; }
        public string LOGGUID { get; set; }
        public string USERCODE { get; set; }
        public string USERNAME { get; set; }
        public string MACHINEIP { get; set; }
        public string MACHINENAME { get; set; }
        public string SOURCETYPE { get; set; }
        public string SOURCE { get; set; }
        public string MESSAGE { get; set; }
        public string EXCEPTION { get; set; }
    }
}
