//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SYS_PERSONALDESKTOP
    {
        public decimal PERSONALDESKTOPID { get; set; }
        public decimal SYSTEMRIGHTID { get; set; }
        public decimal USERID { get; set; }
        public decimal SYSTEMID { get; set; }
        public Nullable<decimal> SORTORDER { get; set; }
        public Nullable<decimal> DISPLAYTYPE { get; set; }
    }
}
