//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SYS_USER
    {
        public decimal USERID { get; set; }
        public Nullable<System.Guid> USERGUID { get; set; }
        public string USERNAME { get; set; }
        public string ACCOUNT { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<decimal> SORTINDEX { get; set; }
        public Nullable<decimal> USERTYPE { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string ISDELETED { get; set; }
        public Nullable<decimal> DEFAULTSYSTEMID { get; set; }
        public Nullable<decimal> DEFAULTLOAD { get; set; }
    }
}
