//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SYS_ROLE
    {
        public decimal ROLEID { get; set; }
        public Nullable<System.Guid> ROLEGUID { get; set; }
        public Nullable<decimal> SYSTEMID { get; set; }
        public string ROLENAME { get; set; }
        public Nullable<decimal> ROLETYPE { get; set; }
        public Nullable<decimal> SORTINDEX { get; set; }
        public string DESCRIPTION { get; set; }
        public string ISDISABLE { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public string ADDER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATER { get; set; }
        public string ISDELETE { get; set; }
        public string ISADMIN { get; set; }
    }
}
