//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SEARCH_TREND_DATE
    {
        public UT_SEARCH_TREND_DATE()
        {
            this.UT_SEARCH_TREND_DATEDT = new HashSet<UT_SEARCH_TREND_DATEDT>();
        }
    
        public System.Guid OID { get; set; }
        public Nullable<System.Guid> SUITEOID { get; set; }
        public string SEARCHDATE { get; set; }
        public string ISCONTRAST { get; set; }
        public string DATATYPE { get; set; }
    
        public virtual ICollection<UT_SEARCH_TREND_DATEDT> UT_SEARCH_TREND_DATEDT { get; set; }
    }
}
