//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SEARCH_CONTRASTPART_DATE
    {
        public System.Guid OID { get; set; }
        public Nullable<System.Guid> SUITEOID { get; set; }
        public string SEARCHYEAR { get; set; }
        public string SEARCHMONTH { get; set; }
        public string CONTRASTYEAR { get; set; }
        public string CONTRASTMONTH { get; set; }
        public string CIRCLEYEAR { get; set; }
        public string CIRCLEMONTH { get; set; }
        public string DATATYPE { get; set; }
        public string ISCONTRAST { get; set; }
        public string ISCIRCLE { get; set; }
    }
}
