//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SEARCH_TREND_DATEDT
    {
        public System.Guid OID { get; set; }
        public Nullable<System.Guid> TRENDOID { get; set; }
        public string CONTRASTYEAR { get; set; }
        public string CONTRASTMONTH { get; set; }
        public string SEARCHYEAR { get; set; }
        public string SEARCHMONTH { get; set; }
    
        public virtual UT_SEARCH_TREND_DATE UT_SEARCH_TREND_DATE { get; set; }
    }
}
