//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SYS_RIGHT
    {
        public decimal RIGHTID { get; set; }
        public decimal SYSTEMID { get; set; }
        public decimal PARENTRIGHTID { get; set; }
        public string RIGHTNAME { get; set; }
        public decimal TYPE { get; set; }
        public string ISADMINRGIHT { get; set; }
        public string NAVIGATEURL { get; set; }
        public string NAVIGATEURL2 { get; set; }
        public string IMAGEURL { get; set; }
        public string SIMAGEURL { get; set; }
        public decimal SORTORDER { get; set; }
        public string ISDISPLAY { get; set; }
        public string ISDELETED { get; set; }
        public string TARGET { get; set; }
        public Nullable<decimal> RIGHTLEVEL { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
    }
}
