//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SYS_LOG
    {
        public decimal LOGID { get; set; }
        public System.DateTime LOGTIME { get; set; }
        public string USERCODE { get; set; }
        public string USERNAME { get; set; }
        public string MACHINEIP { get; set; }
        public string OPERATEMODULE { get; set; }
        public string OPERATETYPE { get; set; }
        public string OPERATEDESC { get; set; }
    }
}
