//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SYS_ORGANIZATION
    {
        public decimal ORGID { get; set; }
        public Nullable<System.Guid> ORGGUID { get; set; }
        public string ORGNAME { get; set; }
        public Nullable<decimal> ORGTYPE { get; set; }
        public string ORGNUMBER { get; set; }
        public Nullable<decimal> ORGPARENTID { get; set; }
        public string ORGEMAIL { get; set; }
        public string ORGPHONE { get; set; }
        public string ORGADDRESS { get; set; }
        public string ORGLEGAL { get; set; }
        public string ORGFAX { get; set; }
        public string CHARGEPERSON { get; set; }
        public string ORGLINKMAN { get; set; }
        public string LINKPHONE { get; set; }
        public string LINKMOBILE { get; set; }
        public string LINKEMAIL { get; set; }
        public Nullable<decimal> SORTINDEX { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string ISDELETED { get; set; }
        public Nullable<decimal> ORGLEVEL { get; set; }
    }
}
