//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SYS_CODEGROUP
    {
        public System.Guid CODEGROUPID { get; set; }
        public string CODEGROUPKEY { get; set; }
        public string CODEGROUPNAME { get; set; }
        public Nullable<decimal> SORTORDER { get; set; }
        public string MEMO { get; set; }
        public string ISDELETED { get; set; }
        public string ADDER { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public string UPDATER { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
