//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SYS_SYSTEM
    {
        public decimal SYSTEMID { get; set; }
        public string SYSTEMNAME { get; set; }
        public decimal SYSTEMTYPE { get; set; }
        public decimal SORTINDEX { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public string ISDELETED { get; set; }
        public string DEFAULTTHEME { get; set; }
        public string IMAGEURL { get; set; }
        public Nullable<decimal> SCREENINDEX { get; set; }
    }
}
