//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SEARCH_TREND_NODE
    {
        public System.Guid OID { get; set; }
        public Nullable<System.Guid> SUITEOID { get; set; }
        public string DIRECTORYID { get; set; }
        public string ISDIRECTORY { get; set; }
        public Nullable<decimal> LEVELS { get; set; }
        public string CODETYPE { get; set; }
    }
}
