//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_AUTO_PARAMS_INFO
    {
        public Nullable<System.Guid> KeyID { get; set; }
        public string object_name { get; set; }
        public string argument_name { get; set; }
        public string data_type { get; set; }
        public Nullable<short> position { get; set; }
        public string argument_value { get; set; }
        public string in_out { get; set; }
        public string PARAMDESCRIPTION { get; set; }
        public Nullable<System.Guid> INFOOID { get; set; }
        public Nullable<System.Guid> PARAMOID { get; set; }
        public string BOOKMARKSNAMES { get; set; }
    }
}
