//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_AUTO_INFO
    {
        public Nullable<System.Guid> KeyID { get; set; }
        public string OBJECT_NAME { get; set; }
        public string PROCDESCRIPTION { get; set; }
        public Nullable<System.Guid> INFOOID { get; set; }
        public string ISDISABLE { get; set; }
        public string MODELNAME { get; set; }
        public string MODELURL { get; set; }
        public Nullable<int> SORTINDEX { get; set; }
    }
}
