//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_SYS_USER
    {
        public decimal KEYID { get; set; }
        public string USERNAME { get; set; }
        public string ACCOUNT { get; set; }
        public Nullable<decimal> USERTYPE { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public Nullable<decimal> SEX { get; set; }
        public Nullable<decimal> ORGID { get; set; }
        public string ORGNAME { get; set; }
        public Nullable<System.Guid> ORGGUID { get; set; }
        public string MOBILEPHONE { get; set; }
        public Nullable<decimal> SORTINDEX { get; set; }
        public string ROLENAME { get; set; }
    }
}
