//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnPan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_SEARCH_GETCHOOSEROOT
    {
        public Nullable<System.Guid> KeyID { get; set; }
        public Nullable<System.Guid> SUITEOID { get; set; }
        public string SHOWNAME { get; set; }
        public string CODETYPE { get; set; }
        public string DirName { get; set; }
        public string SortIndex { get; set; }
        public string CategoryName { get; set; }
        public string ORDERID { get; set; }
        public System.Guid OID { get; set; }
    }
}
